// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myblog/internal/dao/internal"
)

// internalArticleCategoryRelDao is internal type for wrapping internal DAO implements.
type internalArticleCategoryRelDao = *internal.ArticleCategoryRelDao

// articleCategoryRelDao is the data access object for table article_category_rel.
// You can define custom methods on it to extend its functionality as you wish.
type articleCategoryRelDao struct {
	internalArticleCategoryRelDao
}

var (
	// ArticleCategoryRel is globally public accessible object for table article_category_rel operations.
	ArticleCategoryRel = articleCategoryRelDao{
		internal.NewArticleCategoryRelDao(),
	}
)

// Fill with you ideas below.
