// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myblog/internal/dao/internal"
)

// internalArticleContentDao is internal type for wrapping internal DAO implements.
type internalArticleContentDao = *internal.ArticleContentDao

// articleContentDao is the data access object for table article_content.
// You can define custom methods on it to extend its functionality as you wish.
type articleContentDao struct {
	internalArticleContentDao
}

var (
	// ArticleContent is globally public accessible object for table article_content operations.
	ArticleContent = articleContentDao{
		internal.NewArticleContentDao(),
	}
)

// Fill with you ideas below.
