// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myblog/internal/dao/internal"
)

// internalArticleTagRelDao is internal type for wrapping internal DAO implements.
type internalArticleTagRelDao = *internal.ArticleTagRelDao

// articleTagRelDao is the data access object for table article_tag_rel.
// You can define custom methods on it to extend its functionality as you wish.
type articleTagRelDao struct {
	internalArticleTagRelDao
}

var (
	// ArticleTagRel is globally public accessible object for table article_tag_rel operations.
	ArticleTagRel = articleTagRelDao{
		internal.NewArticleTagRelDao(),
	}
)

// Fill with you ideas below.
