// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myblog/internal/dao/internal"
)

// internalStatisticsArticlePvDao is internal type for wrapping internal DAO implements.
type internalStatisticsArticlePvDao = *internal.StatisticsArticlePvDao

// statisticsArticlePvDao is the data access object for table statistics_article_pv.
// You can define custom methods on it to extend its functionality as you wish.
type statisticsArticlePvDao struct {
	internalStatisticsArticlePvDao
}

var (
	// StatisticsArticlePv is globally public accessible object for table statistics_article_pv operations.
	StatisticsArticlePv = statisticsArticlePvDao{
		internal.NewStatisticsArticlePvDao(),
	}
)

// Fill with you ideas below.
